[theme]
base = "light"
primaryColor = "#3b82f6"
backgroundColor = "#f8fafc"
# 👇 把这个颜色改浅，这样主页里的上传框、下拉菜单就会变回清爽的浅色！
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"
font = "sans serif"

[client]
showSidebarNavigation = false